dist: focal

notifications:
  email:
    on_success: change
    on_failure: change

sudo: false
language: python
python:
  - "3.8"
  - "3.9"

install:
  - pip install -U pip wheel tox-travis tox-envfile
#  - pip install -r requirements.txt -r testing/requirements.txt

script: tox
  - pytest -vv -s --flake8 --config=setup.cfg
  - tox 
