import redis
from . import configuration as configuration
from typing import Any

logger: Any

class RedisLiteException(Exception): ...
class RedisLiteServerStartError(Exception): ...

class RedisMixin:
    redis_dir: Any = ...
    pidfile: Any = ...
    socket_file: Any = ...
    connection: Any = ...
    start_timeout: int = ...
    running: bool = ...
    dbfilename: str = ...
    dbdir: Any = ...
    settingregistryfile: Any = ...
    cleanupregistry: bool = ...
    redis_configuration: Any = ...
    redis_configuration_filename: Any = ...
    server_config: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __del__(self) -> None: ...
    def redis_log_tail(self, lines: int = ..., width: int = ...): ...
    @property
    def redis_log(self): ...
    @property
    def db(self): ...
    @property
    def pid(self): ...

class Redis(RedisMixin, redis.Redis): ...
class StrictRedis(RedisMixin, redis.StrictRedis): ...
