from .__init__ import __git_branch__ as __git_branch__, __git_hash__ as __git_hash__, __git_origin__ as __git_origin__, __git_version__ as __git_version__, __redis_executable__ as __redis_executable__, __redis_server_info__ as __redis_server_info__, __source_url__ as __source_url__

def debug_info_list(): ...
def debug_info(): ...
def print_debug_info() -> None: ...
