from .client import Redis as Redis, StrictRedis as StrictRedis
from typing import Any, Optional

logger: Any
original_classes: Any
Redis_Patched: bool
StrictRedis_Patched: bool

def patch_redis_Redis(dbfile: Optional[Any] = ...) -> None: ...
def unpatch_redis_Redis() -> None: ...
def patch_redis_StrictRedis(dbfile: Optional[Any] = ...) -> None: ...
def unpatch_redis_StrictRedis() -> None: ...
def patch_redis(dbfile: Optional[Any] = ...) -> None: ...
def unpatch_redis() -> None: ...
